package com.example.tokyorestauranttakeout.entity;

import java.util.Date;

public class AdminRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.id
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.name
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.created_at
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.updated_at
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.id
     *
     * @return the value of admin_role.id
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.id
     *
     * @param id the value for admin_role.id
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.name
     *
     * @return the value of admin_role.name
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.name
     *
     * @param name the value for admin_role.name
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.created_at
     *
     * @return the value of admin_role.created_at
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.created_at
     *
     * @param createdAt the value for admin_role.created_at
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.updated_at
     *
     * @return the value of admin_role.updated_at
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.updated_at
     *
     * @param updatedAt the value for admin_role.updated_at
     *
     * @mbg.generated Mon May 03 09:47:41 JST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}