package com.example.tokyorestauranttakeout.entity;

import java.util.Date;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.text
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.sender_mail_address
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    private String senderMailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.resolved_flg
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    private Boolean resolvedFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.created_at
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.updated_at
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.text
     *
     * @return the value of question.text
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.text
     *
     * @param text the value for question.text
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.sender_mail_address
     *
     * @return the value of question.sender_mail_address
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public String getSenderMailAddress() {
        return senderMailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.sender_mail_address
     *
     * @param senderMailAddress the value for question.sender_mail_address
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public void setSenderMailAddress(String senderMailAddress) {
        this.senderMailAddress = senderMailAddress == null ? null : senderMailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.resolved_flg
     *
     * @return the value of question.resolved_flg
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public Boolean getResolvedFlg() {
        return resolvedFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.resolved_flg
     *
     * @param resolvedFlg the value for question.resolved_flg
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public void setResolvedFlg(Boolean resolvedFlg) {
        this.resolvedFlg = resolvedFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.created_at
     *
     * @return the value of question.created_at
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.created_at
     *
     * @param createdAt the value for question.created_at
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.updated_at
     *
     * @return the value of question.updated_at
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.updated_at
     *
     * @param updatedAt the value for question.updated_at
     *
     * @mbg.generated Sat Sep 05 11:13:26 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}