package com.example.tokyorestauranttakeout.entity;

public class RestaurantWithBLOBs extends Restaurant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.image
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.introduction
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.image
     *
     * @return the value of restaurant.image
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.image
     *
     * @param image the value for restaurant.image
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.introduction
     *
     * @return the value of restaurant.introduction
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.introduction
     *
     * @param introduction the value for restaurant.introduction
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}