package com.example.tokyorestauranttakeout.entity;

import java.util.Date;

public class WardArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward_area.id
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward_area.name
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward_area.mime_type
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    private String mimeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward_area.ward_id
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    private Integer wardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward_area.created_at
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward_area.updated_at
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward_area.image
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward_area.id
     *
     * @return the value of ward_area.id
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward_area.id
     *
     * @param id the value for ward_area.id
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward_area.name
     *
     * @return the value of ward_area.name
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward_area.name
     *
     * @param name the value for ward_area.name
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward_area.mime_type
     *
     * @return the value of ward_area.mime_type
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public String getMimeType() {
        return mimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward_area.mime_type
     *
     * @param mimeType the value for ward_area.mime_type
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType == null ? null : mimeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward_area.ward_id
     *
     * @return the value of ward_area.ward_id
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public Integer getWardId() {
        return wardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward_area.ward_id
     *
     * @param wardId the value for ward_area.ward_id
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public void setWardId(Integer wardId) {
        this.wardId = wardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward_area.created_at
     *
     * @return the value of ward_area.created_at
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward_area.created_at
     *
     * @param createdAt the value for ward_area.created_at
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward_area.updated_at
     *
     * @return the value of ward_area.updated_at
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward_area.updated_at
     *
     * @param updatedAt the value for ward_area.updated_at
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward_area.image
     *
     * @return the value of ward_area.image
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward_area.image
     *
     * @param image the value for ward_area.image
     *
     * @mbg.generated Thu Jun 25 18:42:07 JST 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}