package com.example.tokyorestauranttakeout.mapper;

import com.example.tokyorestauranttakeout.entity.Restaurant;
import com.example.tokyorestauranttakeout.entity.RestaurantExample;
import com.example.tokyorestauranttakeout.entity.RestaurantWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    long countByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    int deleteByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    int insert(RestaurantWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    int insertSelective(RestaurantWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    List<RestaurantWithBLOBs> selectByExampleWithBLOBs(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    List<Restaurant> selectByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    RestaurantWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    int updateByExampleSelective(@Param("record") RestaurantWithBLOBs record, @Param("example") RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") RestaurantWithBLOBs record, @Param("example") RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    int updateByExample(@Param("record") Restaurant record, @Param("example") RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    int updateByPrimaryKeySelective(RestaurantWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    int updateByPrimaryKeyWithBLOBs(RestaurantWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Wed Aug 05 08:01:13 JST 2020
     */
    int updateByPrimaryKey(Restaurant record);
}