package com.example.tokyorestauranttakeout.mapper;

import com.example.tokyorestauranttakeout.entity.Ward;
import com.example.tokyorestauranttakeout.entity.WardExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface WardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    long countByExample(WardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    int deleteByExample(WardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    int insert(Ward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    int insertSelective(Ward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    List<Ward> selectByExampleWithBLOBs(WardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    List<Ward> selectByExample(WardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    Ward selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    int updateByExampleSelective(@Param("record") Ward record, @Param("example") WardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Ward record, @Param("example") WardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    int updateByExample(@Param("record") Ward record, @Param("example") WardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    int updateByPrimaryKeySelective(Ward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Ward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward
     *
     * @mbg.generated Thu Jun 10 06:40:33 JST 2021
     */
    int updateByPrimaryKey(Ward record);
}